### ISSUE TITLE
Outscale LBU not working properly

### ISSUE THREAD

**Issue by andronux** [outscale-dev/exercising-k8s-the-hardway#1]
Hello,

I'm trying to make the LBU work with my control plane.

The HTTPS listener simply doesn't work although everything is configured as it should be.

Same thing for the health check. I see no traffic coming from the loadbalancer on my instance (checked with ngrep).

Am I missing something?

Thanks for your help!

![image](https://user-images.githubusercontent.com/31890696/140638649-b402e75a-b98f-4a4e-86a8-c869846239df.png)
![image](https://user-images.githubusercontent.com/31890696/140638662-b2f472da-2d76-4dd9-aa4f-a8513ec83e48.png)
![image](https://user-images.githubusercontent.com/31890696/140638775-3a43fea7-b696-4456-a293-0ad6c7a2e361.png)

**Comment by jerome-jutteau** [comment]
Hi!

Are you using this project to deploy your load balancer? Did you make any change?
A technic to debug your load balancer is to first ensure that the service behind is available and can accept connexions on the port.

If it helps, you can check an exemple of kubernetes API load balancing in [kubernetes-lb.tf](https://github.com/outscale-dev/exercising-k8s-the-hardway/blob/951ab505fc5eaf6efd1faff1e71a206f2de48eae/kubernetes-lb.tf)

**Comment by jerome-jutteau** [comment]
Hi,

I re-read again your issue and noticed that you are using `HTTPS`. Maybe check your [SSL configuration](https://docs.outscale.com/en/userguide/Configuring-a-Load-Balancer-for-SSL-Termination-or-SSL-Passthrough.html) or try with TCP if your instances are able to terminate SSL traffic.

**Comment by andronux** [comment]
Hi @jerome-jutteau , thank you for your comments. But it looks like the issue were on your side following a ticket opened with your support.

We can close this issue.

Thank you anyway.

**Comment by jerome-jutteau** [comment]
Feel free to open an issue here as needed. Note that you can also test deploying a cluster based on RKE in [outscale-dev/osc-k8s-rke-cluster](https://github.com/outscale-dev/osc-k8s-rke-cluster).
