### ISSUE TITLE
coredns indent issue

### ISSUE THREAD

**Issue by albundy83** [outscale-dev/exercising-k8s-the-hardway#5]
Hello,

this line https://github.com/outscale-dev/exercising-k8s-the-hardway/blob/2d4a1a6b9579da749eeb22ebcff0beae69865e86/coredns.tf#L6 must be replaced by
```bash
sed -i "s%loadbalance%loadbalance\n        forward . /etc/resolv%" coredns/coredns-1.8.yaml
```
As tabulation cause issue in the generated yaml file.

**Comment by jerome-jutteau** [comment]
Thanks for pointing out this issue!
